server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fraud
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
#server:
#  port: 8084
#spring:
#  application:
#    name: customer
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    password: root
#    url: jdbc:postgresql://localhost:5432/customer
#    username: postgres
#    jpa:
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect
#          format_sql: 'true'
#
#      hibernate:
#        ddl-auto: create
#      show-sql: 'true'